from __future__ import annotations

_DASHBOARD_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shreks Operator Dashboard</title>
<style>
:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:#0b0e0d;color:#e8efe9}*{box-sizing:border-box}body{margin:0}.shell{max-width:1180px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:18px}h1{font-size:1.35rem;margin:0 0 5px}.muted{color:#97a69a}.live{border:1px solid #7d3c3c;background:#241313;color:#ffb6b6;border-radius:10px;padding:10px 12px;font-weight:800}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{border:1px solid #27312a;background:#111613;border-radius:12px;padding:14px;min-width:0}.card h2{font-size:1rem;margin:0 0 12px}.metrics,.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.metric{border-top:1px solid #222b25;padding-top:7px}.label{display:block;color:#97a69a;font-size:.72rem}.value{display:block;overflow-wrap:anywhere}.wide{grid-column:1/-1}.controls{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.control-button{border:1px solid #55635a;background:#18201b;color:#e8efe9;border-radius:9px;padding:10px 12px;font:inherit;font-weight:800;cursor:pointer}.control-button.danger{border-color:#9b4141;background:#321717;color:#ffd0d0}.control-button:disabled{opacity:.4;cursor:not-allowed}.control-note{margin-top:10px;font-size:.76rem;color:#97a69a}.attention-list{margin:10px 0 0;padding-left:20px}.attention-list li{margin:5px 0;overflow-wrap:anywhere}.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:.82rem}th,td{text-align:left;padding:8px;border-bottom:1px solid #222b25;white-space:nowrap}tbody tr{cursor:pointer}tbody tr:hover,tbody tr:focus{background:#19201b;outline:none}.footer{margin-top:14px;color:#718077;font-size:.72rem}@media(max-width:760px){.shell{padding:12px}.grid,.metrics,.detail-grid{grid-template-columns:1fr}.wide{grid-column:auto}.controls{display:grid}}
</style>
</head>
<body>
<main class="shell">
<header class="top"><div><h1>Shreks Operator Dashboard</h1><div class="muted">PAPER operations view · safety controls only · <span id="generated-at">UNAVAILABLE</span></div></div><div class="live">LIVE TRADING: DISABLED</div></header>
<section class="grid" aria-label="Monitoring layers">
<article class="card wide" id="attention-layer"><h2>Attention / Problems</h2><div id="attention-status" class="muted">UNAVAILABLE</div><ul id="attention-list" class="attention-list"></ul></article>
<article class="card wide" id="emergency-controls"><h2>Emergency controls</h2><div class="metrics">
<div class="metric"><span class="label">Availability</span><span class="value" id="control-availability">UNAVAILABLE</span></div><div class="metric"><span class="label">Revision</span><span class="value" id="control-revision">UNAVAILABLE</span></div><div class="metric"><span class="label">Entry halt</span><span class="value" id="control-entry-halt">UNAVAILABLE</span></div><div class="metric"><span class="label">Kill switch</span><span class="value" id="control-kill-switch">UNAVAILABLE</span></div><div class="metric"><span class="label">Last command</span><span class="value" id="control-last-command">UNAVAILABLE</span></div><div class="metric"><span class="label">Updated</span><span class="value" id="control-updated-at">UNAVAILABLE</span></div>
</div><div class="controls"><button class="control-button" type="button" id="halt-new-entries" disabled>HALT NEW ENTRIES</button><button class="control-button danger" type="button" id="emergency-kill" disabled>EMERGENCY KILL SWITCH</button></div><div class="control-note" id="control-action-state">Safety actions only. Clearing or resetting controls is host-only.</div></article>
<article class="card" id="system-layer"><h2>System</h2><div class="metrics">
<div class="metric"><span class="label">Status</span><span class="value" id="system-status">UNAVAILABLE</span></div><div class="metric"><span class="label">Market age</span><span class="value" id="market-age">UNAVAILABLE</span></div><div class="metric"><span class="label">Providers</span><span class="value" id="provider-health">UNAVAILABLE</span></div><div class="metric"><span class="label">Accounting</span><span class="value" id="accounting-status">UNAVAILABLE</span></div><div class="metric"><span class="label">Latest checkpoint</span><span class="value" id="checkpoint-at">UNAVAILABLE</span></div><div class="metric"><span class="label">Host metrics</span><span class="value" id="host-metrics">UNAVAILABLE</span></div>
</div></article>
<article class="card" id="trading-layer"><h2>Trading</h2><div class="metrics">
<div class="metric"><span class="label">Status</span><span class="value" id="trading-status">UNAVAILABLE</span></div><div class="metric"><span class="label">Candidates</span><span class="value" id="candidate-count">UNAVAILABLE</span></div><div class="metric"><span class="label">Paper entries</span><span class="value" id="entry-count">UNAVAILABLE</span></div><div class="metric"><span class="label">Open positions</span><span class="value" id="open-count">UNAVAILABLE</span></div><div class="metric"><span class="label">Closed positions</span><span class="value" id="closed-count">UNAVAILABLE</span></div><div class="metric"><span class="label">Candidate version</span><span class="value" id="candidate-version">UNAVAILABLE</span></div>
</div></article>
<article class="card" id="money-layer"><h2>Money</h2><div class="metrics">
<div class="metric"><span class="label">Status</span><span class="value" id="money-status">UNAVAILABLE</span></div><div class="metric"><span class="label">Realized PnL</span><span class="value" id="realized-pnl">UNAVAILABLE</span></div><div class="metric"><span class="label">Unrealized PnL</span><span class="value" id="unrealized-pnl">UNAVAILABLE</span></div><div class="metric"><span class="label">Net expectancy</span><span class="value" id="net-expectancy">UNAVAILABLE</span></div><div class="metric"><span class="label">Profit factor</span><span class="value" id="profit-factor">UNAVAILABLE</span></div><div class="metric"><span class="label">Maximum drawdown</span><span class="value" id="max-drawdown">UNAVAILABLE</span></div><div class="metric"><span class="label">Total costs</span><span class="value" id="total-costs">UNAVAILABLE</span></div><div class="metric"><span class="label">Cost burden</span><span class="value" id="cost-burden">UNAVAILABLE</span></div>
</div></article>
<article class="card" id="proof-risk-layer"><h2>Proof / Risk</h2><div class="metrics">
<div class="metric"><span class="label">Status</span><span class="value" id="proof-status">UNAVAILABLE</span></div><div class="metric"><span class="label">Proof decision</span><span class="value" id="proof-decision">UNAVAILABLE</span></div><div class="metric"><span class="label">Promotion decision</span><span class="value" id="promotion-decision">UNAVAILABLE</span></div><div class="metric"><span class="label">Proof trades</span><span class="value" id="proof-trades">UNAVAILABLE</span></div><div class="metric"><span class="label">Distinct mints</span><span class="value" id="proof-mints">UNAVAILABLE</span></div><div class="metric"><span class="label">Global risk state</span><span class="value" id="risk-halt">UNAVAILABLE</span></div><div class="metric"><span class="label">Accounting integrity</span><span class="value" id="accounting-integrity">UNAVAILABLE</span></div><div class="metric"><span class="label">Live state</span><span class="value" id="live-state">DISABLED</span></div>
</div></article>
<article class="card wide" id="recent-trades"><h2>Recent trades</h2><div id="trades-state" class="muted">UNAVAILABLE</div><div class="table-wrap"><table><thead><tr><th>Closed</th><th>Mint</th><th>Setup</th><th>Regime</th><th>Net PnL</th><th>Friction</th><th>Explicit cost</th></tr></thead><tbody id="trades-body"></tbody></table></div></article>
<article class="card wide" id="trade-detail"><h2>Trade detail</h2><div id="detail-state" class="muted">Select a recent trade. Missing historical decision evidence is shown as NOT_PERSISTED.</div><div class="detail-grid"><div><span class="label">Position</span><span class="value" id="detail-position">UNAVAILABLE</span></div><div><span class="label">Mint</span><span class="value" id="detail-mint">UNAVAILABLE</span></div><div><span class="label">Net PnL</span><span class="value" id="detail-pnl">UNAVAILABLE</span></div><div><span class="label">Safety assessment</span><span class="value" id="detail-safety">NOT_PERSISTED</span></div><div><span class="label">Feature vector</span><span class="value" id="detail-features">NOT_PERSISTED</span></div><div><span class="label">Score assessment</span><span class="value" id="detail-score">NOT_PERSISTED</span></div><div><span class="label">Entry decision</span><span class="value" id="detail-decision">NOT_PERSISTED</span></div><div><span class="label">Risk assessment</span><span class="value" id="detail-risk">NOT_PERSISTED</span></div><div><span class="label">Entry quote</span><span class="value" id="detail-quote">NOT_PERSISTED</span></div><div><span class="label">Strategic exit reason</span><span class="value" id="detail-exit">NOT_PERSISTED</span></div></div><div><span class="label">Ledger events</span><span class="value" id="detail-ledger">UNAVAILABLE</span></div></article>
</section>
<div class="footer">Metrics come from persisted Shreks telemetry and evidence. This page formats values; it does not derive trading performance or proof decisions. Operator controls write only the revisioned risk-control state.</div>
</main>
<script>
"use strict";
const byId=(id)=>document.getElementById(id);
const setText=(id,value)=>{byId(id).textContent=value===null||value===undefined?"UNAVAILABLE":String(value);};
const money=(value)=>value===null||value===undefined?"UNAVAILABLE":`$${Number(value).toFixed(2)}`;
const percent=(value)=>value===null||value===undefined?"UNAVAILABLE":`${Number(value).toFixed(2)}%`;
const when=(value)=>value===null||value===undefined?"UNAVAILABLE":new Date(value).toLocaleString();
const yesNo=(value)=>value===null||value===undefined?"UNAVAILABLE":value?"YES":"NO";
const haltButton=byId("halt-new-entries");
const killButton=byId("emergency-kill");
let controlState=null;
let latestTelemetry=null;
function addAttention(items,message){if(!items.includes(message)){items.push(message);}}
function renderAttention(){const list=byId("attention-list");list.replaceChildren();if(!latestTelemetry){setText("attention-status","SOURCE_UNAVAILABLE");return;}const t=latestTelemetry,s=t.system,r=t.trading,m=t.money,p=t.proof_risk;const items=[];
if(t.overall_status!=="HEALTHY"){addAttention(items,`Overall telemetry: ${t.overall_status}`);}if(s.status!=="HEALTHY"){addAttention(items,`System layer: ${s.status}`);}if(r.status!=="HEALTHY"){addAttention(items,`Trading layer: ${r.status}`);}if(m.status!=="HEALTHY"){addAttention(items,`Money layer: ${m.status}`);}if(p.status!=="HEALTHY"){addAttention(items,`Proof / Risk layer: ${p.status}`);}if(Number(s.unhealthy_provider_count)>0){addAttention(items,`Unhealthy providers: ${s.unhealthy_provider_count}`);}if(s.latest_ingestion_checkpoint_at_unix_ms===null){addAttention(items,"Ingestion checkpoint unavailable");}if(s.accounting_status!=="VALID"){addAttention(items,`System accounting: ${s.accounting_status??"UNAVAILABLE"}`);}if(p.accounting_integrity!=="VALID"){addAttention(items,`Accounting integrity: ${p.accounting_integrity??"UNAVAILABLE"}`);}if(p.global_risk_halt===true){addAttention(items,"Global risk halt active");}if(p.kill_switch_active===true){addAttention(items,"Telemetry kill switch active");}
for(const layer of [s,r,m,p]){for(const error of Array.isArray(layer.source_errors)?layer.source_errors:[]){addAttention(items,`Source error: ${error}`);}}
if(controlState?.halt_new_entries===true){addAttention(items,"Operator entry halt active");}if(controlState?.kill_switch_active===true){addAttention(items,"Operator kill switch active");}
if(items.length===0){setText("attention-status","OK");const item=document.createElement("li");item.textContent="No active problems detected";list.append(item);return;}setText("attention-status",`${items.length} active item${items.length===1?"":"s"}`);for(const message of items){const item=document.createElement("li");item.textContent=message;list.append(item);}}
function renderSnapshot(payload){const t=payload.telemetry,s=t.system,r=t.trading,m=t.money,p=t.proof_risk,e=m.performance;latestTelemetry=t;
setText("generated-at",when(t.generated_at_unix_ms));setText("system-status",s.status);setText("market-age",s.market_age_ms===null?null:`${s.market_age_ms} ms`);setText("provider-health",s.provider_count===null?null:`${s.provider_count} total · ${s.unhealthy_provider_count} unhealthy`);setText("accounting-status",s.accounting_status);setText("checkpoint-at",when(s.latest_ingestion_checkpoint_at_unix_ms));setText("host-metrics",yesNo(s.host_metrics_available));
setText("trading-status",r.status);setText("candidate-count",r.candidate_count);setText("entry-count",r.terminal_paper_entry_count);setText("open-count",r.open_position_count);setText("closed-count",r.closed_position_count);setText("candidate-version",r.candidate_version);
setText("money-status",m.status);setText("realized-pnl",money(m.realized_pnl_usd));setText("unrealized-pnl",money(m.unrealized_pnl_usd));setText("net-expectancy",e?percent(e.net_expectancy_pct):null);setText("profit-factor",e?e.profit_factor:null);setText("max-drawdown",e?percent(e.maximum_drawdown_pct):null);setText("total-costs",e?money(e.total_cost_usd):null);setText("cost-burden",e?percent(e.cost_burden_pct):null);
setText("proof-status",p.status);setText("proof-decision",p.proof_decision);setText("promotion-decision",p.promotion_decision);setText("proof-trades",p.proof_trade_count);setText("proof-mints",p.proof_distinct_mint_count);setText("risk-halt",yesNo(p.global_risk_halt));setText("accounting-integrity",p.accounting_integrity);setText("live-state",p.live_state);renderAttention();
// Authoritative fields: net_pnl_usd unrealized_pnl_usd net_expectancy_pct profit_factor maximum_drawdown_pct total_cost_usd cost_burden_pct proof_trade_count proof_distinct_mint_count proof_decision promotion_decision global_risk_halt accounting_integrity
}
function renderControls(){if(!controlState){haltButton.disabled=true;killButton.disabled=true;setText("control-revision",null);setText("control-entry-halt",null);setText("control-kill-switch",null);setText("control-last-command",null);setText("control-updated-at",null);renderAttention();return;}setText("control-availability","AVAILABLE");setText("control-revision",controlState.revision);setText("control-entry-halt",yesNo(controlState.halt_new_entries));setText("control-kill-switch",yesNo(controlState.kill_switch_active));setText("control-last-command",controlState.last_command);setText("control-updated-at",when(controlState.updated_at_unix_ms));haltButton.disabled=!controlState||controlState.halt_new_entries||controlState.kill_switch_active;killButton.disabled=!controlState||controlState.kill_switch_active;renderAttention();}
async function loadControls(){try{const response=await fetch("/api/v1/operator-controls", {credentials: "same-origin"});if(!response.ok){throw new Error("SOURCE_UNAVAILABLE");}controlState=await response.json();renderControls();}catch(_error){controlState=null;setText("control-availability","SOURCE_UNAVAILABLE");setText("control-action-state","Control state unavailable. Buttons disabled.");renderControls();}}
async function postControl(path,body){if(!controlState){return;}haltButton.disabled=true;killButton.disabled=true;setText("control-action-state","Submitting safety command…");try{const response=await fetch(path,{method: "POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-Shreks-CSRF":controlState.csrf_token},body});if(response.status===409){setText("control-action-state","Revision changed. Reloaded authoritative state.");await loadControls();return;}if(!response.ok){throw new Error("CONTROL_REJECTED");}const csrfToken=controlState.csrf_token;controlState=await response.json();controlState.csrf_token=csrfToken;renderControls();setText("control-action-state","Safety command applied.");}catch(_error){setText("control-action-state","SOURCE_UNAVAILABLE");await loadControls();}}
haltButton.addEventListener("click",()=>{if(!controlState){return;}postControl("/api/v1/operator-controls/halt-new-entries",JSON.stringify({expected_revision:controlState.revision}));});
killButton.addEventListener("click",()=>{if(!controlState){return;}if(!window.confirm("EMERGENCY KILL SWITCH will halt new entries and trigger the existing emergency exit path. Continue?")){return;}postControl("/api/v1/operator-controls/emergency-kill",JSON.stringify({confirmation:"EMERGENCY KILL SWITCH",expected_revision:controlState.revision}));});
function makeCell(row,value){const cell=document.createElement("td");cell.textContent=value===null||value===undefined?"UNAVAILABLE":String(value);row.append(cell);}
function renderTrades(payload){const body=byId("trades-body");body.replaceChildren();const trades=Array.isArray(payload.trades)?payload.trades:[];setText("trades-state",trades.length?`${trades.length} persisted closed trades`:"No persisted closed trades");for(const trade of trades){const row=document.createElement("tr");row.tabIndex=0;row.setAttribute("role","button");makeCell(row,when(trade.closed_at_unix_ms));makeCell(row,trade.mint);makeCell(row,trade.setup_name);makeCell(row,trade.market_regime);makeCell(row,money(trade.net_pnl_usd));makeCell(row,money(trade.execution_friction_usd));makeCell(row,money(trade.explicit_cost_usd));const open=()=>loadTrade(trade.position_id);row.addEventListener("click",open);row.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open();}});body.append(row);}}
async function loadTrade(positionId){setText("detail-state","Loading persisted evidence…");try{const response=await fetch(`/api/v1/trades/${encodeURIComponent(positionId)}`, {credentials: "same-origin"});if(!response.ok){throw new Error("SOURCE_UNAVAILABLE");}const d=await response.json();setText("detail-state","Persisted trade evidence");setText("detail-position",d.summary.position_id);setText("detail-mint",d.summary.mint);setText("detail-pnl",money(d.summary.net_pnl_usd));setText("detail-safety",d.safety_assessment);setText("detail-features",d.feature_vector);setText("detail-score",d.score_assessment);setText("detail-decision",d.entry_decision);setText("detail-risk",d.risk_assessment);setText("detail-quote",d.entry_quote);setText("detail-exit",d.strategic_exit_reason);setText("detail-ledger",d.ledger_events.length?d.ledger_events.map(event=>`#${event.sequence} ${event.side} ${event.execution_state} ${money(event.filled_notional_usd)}`).join(" · "):"UNAVAILABLE");}catch(_error){setText("detail-state","SOURCE_UNAVAILABLE");}}
async function refresh(){await loadControls();try{const response=await fetch("/api/v1/snapshot", {credentials: "same-origin"});if(!response.ok){throw new Error("SOURCE_UNAVAILABLE");}renderSnapshot(await response.json());}catch(_error){latestTelemetry=null;setText("generated-at","SOURCE_UNAVAILABLE");renderAttention();}try{const response=await fetch("/api/v1/trades", {credentials: "same-origin"});if(!response.ok){throw new Error("SOURCE_UNAVAILABLE");}renderTrades(await response.json());}catch(_error){setText("trades-state","SOURCE_UNAVAILABLE");}}
refresh();setInterval(refresh,15000);
</script>
</body>
</html>
"""


def render_dashboard_page() -> bytes:
    return _DASHBOARD_HTML.encode("utf-8")
